on: [push, pull_request]
name: PHPMD
jobs:
    phpmd:
        name: PHPMD
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  tools: phpmd
            - name: Run PHPMD
              run: phpmd . github ruleset.xml --exclude 'Tests/*,vendor/*'
