name: "Static analysis - PHPStan"

on:
  push:
    branches: [ master, '*.x' ]
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Setup Composer token
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist

      - name: Prepare PHPStan cache directory
        run: mkdir -p ./tmp/phpstan

      - name: Restore PHPStan result cache
        uses: actions/cache/restore@v4
        with:
          path: ./tmp/phpstan
          key: ${{ runner.os }}-phpstan-result-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpstan-result-cache-

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M --ansi --error-format=github

      - name: Save PHPStan result cache
        uses: actions/cache/save@v4
        if: ${{ !cancelled() }}
        with:
          path: ./tmp/phpstan
          key: phpstan-result-cache-${{ github.sha }}
